--Resolução do bootcamp da DIO e Avanade
-- Desenvolvedor : Ian Bernardo Lima dos Santos

-- QUESTÃO 1
SELECT NOME, ANO
FROM FILMES


-- QUESTÃO 2
SELECT NOME, ANO, DURACAO
FROM FILMES
ORDER BY ANO

-- QUESTÃO 3
SELECT NOME, ANO, DURACAO
FROM FILMES
WHERE NOME LIKE '%De volta para o futuro%'


-- QUESTÃO 4
SELECT NOME, ANO, DURACAO
FROM FILMES
WHERE ANO = 1997

-- QUESTÃO 5
SELECT NOME, ANO, DURACAO
FROM FILMES
WHERE ANO > 2000


-- QUESTÃO 6
SELECT NOME, ANO, DURACAO
FROM FILMES
WHERE DURACAO > 100 and DURACAO < 150
ORDER BY DURACAO


-- QUESTÃO 7

SELECT ANO, COUNT(ID) AS QUANTIDADE
FROM FILMES
GROUP BY ANO
ORDER BY COUNT(ID) DESC

-- QUESTÃO 8
SELECT ID, PrimeiroNome, UltimoNome, GENERO
FROM ATORES
WHERE GENERO = 'M'

-- QUESTÃO 9
SELECT ID, PrimeiroNome, UltimoNome, GENERO
FROM ATORES
WHERE GENERO = 'F'
ORDER BY PrimeiroNome


-- QUESTÃO 10

SELECT F.Nome, G.Genero
FROM FILMES AS F INNER JOIN FILMESGENERO AS FG ON (F.Id = FG.IdFilme)
INNER JOIN Generos AS G ON (FG.IdGenero = G.Id)


-- QUESTÃO 11

SELECT F.Nome, G.Genero
FROM FILMES AS F INNER JOIN FILMESGENERO AS FG ON (F.Id = FG.IdFilme)
INNER JOIN Generos AS G ON (FG.IdGenero = G.Id)
WHERE G.Genero like '%Mistério%'

-- QUESTÃO 12

SELECT F.Nome, A.PrimeiroNome, A.UltimoNome, EF.Papel
FROM FILMES AS F INNER JOIN ElencoFilme AS EF ON (F.Id = EF.IdFilme)
	 INNER JOIN ATORES AS A ON (EF.IdAtor = A.Id)